version: "3.3"
services:
  db:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "gocontacts"
      PGDATA: /pg-data
    volumes:
      - ./docker/data/pg-data:/pg-data
    ports:
      - "127.0.0.1:5432:5432"
  rmq:
    image: rabbitmq:3-management
    volumes:
      - ./docker/data/rmq-data:/var/lib/rabbitmq
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"