version: "3.3"
services:
  db:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "gocontacts"
      PGDATA: /pg-data
    volumes:
      - ./docker/data/pg-data:/pg-data
    ports:
      - "127.0.0.1:5432:5432"


